SELECT  [ProductKey]
      ,[OrderDateKey]-40000 as [OrderDateKey]
      ,[DueDateKey] -40000 as [DueDateKey]
      ,[ShipDateKey] -40000 as [ShipDateKey]
      ,[CustomerKey]
      --,[PromotionKey]
      --,[CurrencyKey]
      --,[SalesTerritoryKey]
      ,[SalesOrderNumber]
      --,[SalesOrderLineNumber]
      --,[RevisionNumber]
      --,[OrderQuantity]
      --,[UnitPrice]
      --,[ExtendedAmount]
      --,[UnitPriceDiscountPct]
      --,[DiscountAmount]
      --,[ProductStandardCost]
      --,[TotalProductCost]
      ,[SalesAmount]
      --,[TaxAmt]
      --,[Freight]
      --,[CarrierTrackingNumber]
      --,[CustomerPONumber]
      --,[OrderDate]
      --,[DueDate]
      --,[ShipDate]
 FROM [AdventureWorksDW2019].[dbo].[FactInternetSales]
 WHERE 
	LEFT(OrderDateKey,4) >= YEAR(GETDATE())-2
ORDER BY
	OrderDateKey ASC